name: Piborg
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5017329666297883
title: Just testing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfcfa'
    - '#151515'
    - '#454344'
    - '#6e6663'
    - '#989896'
  brandStrength: 0.012059689033776522
  lightness: 0.4107443916145712
  saturation: 0.3838336723856628
  rhythmicContrast: 0.6497063480783254
purpose: []
